name: tree_node
description: An all encompassing tree implementation
version: 0.1.0
repository: https://github.com/mcmah309/tree_node

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
